#!/usr/bin/env python

###############################################################
# < next few lines under version control, D O  N O T  E D I T >
# $Date$
# $Revision$
# $Author$
# $Id$
###############################################################

###############################################################
# L96_varDA.py - cycle variational DA on Lorenz & Emanuel 1998
###############################################################

###############################################################
__author__    = "Rahul Mahajan"
__email__     = "rahul.mahajan@nasa.gov"
__copyright__ = "Copyright 2012, NASA / GSFC / GMAO"
__license__   = "GPL"
__status__    = "Prototype"
###############################################################

###############################################################
import sys
import numpy         as     np
from   scipy         import integrate, io
from   matplotlib    import pyplot
from   netCDF4       import Dataset
from   module_Lorenz import L96, plot_L96
from   module_DA     import *
from   module_IO     import *
from   plot_stats    import *
###############################################################

###############################################################
global Ndof, F, dF, lab
global A, Q, H, R
global nassim, ntimes, dt, t0
global Vupdate, minimization
global diag_fname, diag_fattr
global plots_Show, plots_Save

Ndof = 40
F    = 8.0
dF   = 0.1
lab  = []
for j in range(0,Ndof): lab.append( 'x' + str(j+1) )

A = np.eye(Ndof)             # initial analysis error covariance
Q = np.eye(Ndof)*0.0         # model error covariance ( covariance model is white for now)
H = np.eye(Ndof)             # obs operator ( eye(Ndof) gives identity obs )
R = np.eye(Ndof)*(0.2**2)    # observation error covariance

nassim = 200                 # no. of assimilation cycles
dt     = 1.0e-4              # time-step
ntimes = 0.05                # do assimilation every ntimes non-dimensional time units
t0     = 0.0                 # initial time

Vupdate = 1                  # DA method (1= 3Dvar; 2= 4Dvar)
maxiter = 1000               # maximum iterations
alpha   = 4e-3               # size of step in direction of normalized J
cg      = True               # True = Use conjugate gradient; False = Perform line search
minimization = [maxiter, alpha, cg]

# name and attributes of/in the output diagnostic file
diag_fname = 'L96_varDA_diag.nc4'
diag_fattr = {'F'           : str(F),
              'dF'          : str(dF),
              'ntimes'      : str(ntimes),
              'dt'          : str(dt),
              'Vupdate'     : str(Vupdate),
              'maxiter'     : str(maxiter),
              'alpha'       : str(alpha),
              'cg'          : str(int(cg))}
###############################################################

###############################################################
def main():

    # insure the same sequence of random numbers EVERY TIME
    np.random.seed(0)

    # check for valid variational data assimilation options
    check_varDA(Vupdate)

    # initial setup from LE1998
    x0    = np.ones(Ndof) * F
    x0[0] = 1.001 * F

    # Make a copy of truth for plotting later
    xt = x0.copy()

    # populate the initial state by perturbing the true state
    pert = 0.001 * np.random.randn(Ndof)
    xa = xt + pert
    xb = xa.copy()

    # load fixed background error covariance matrix; generated by L96_stats.py and compute inverse
    nc = Dataset('L96_climo_B.nc4','r')
    Bc = nc.variables['B'][:]
    nc.close()

    print 'Cycling ON the attractor ...'

    ts = np.arange(t0,ntimes+dt,dt)     # time between assimilations

    # create diagnostic file
    create_diag(diag_fname, diag_fattr, Ndof)
    write_diag(diag_fname, 0, xt, xb, xa, np.dot(H,xt), H, np.diag(R), niters=np.NaN)

    for k in range(0, nassim):

        print '========== assimilation time = %5d ========== ' % (k+1)

        # advance truth with the full nonlinear model
        xs = integrate.odeint(L96, xt, ts, (F,0.0))
        xt = xs[-1,:].copy()

        # new observations from noise about truth; set verification values
        y   = np.dot(H,xt) + np.random.randn(Ndof) * np.sqrt(np.diag(R))
        ver = xt.copy()

        # step to the next assimilation time
        xs = integrate.odeint(L96, xa, ts, (F+dF,0.0))
        xb = xs[-1,:].copy()

        # update step
        xa, A, niters = update_varDA(xb, Bc, y, R, H, Vupdate=Vupdate, minimization=minimization)

        # write diagnostics to disk
        write_diag(diag_fname, k+1, ver, xb, xa, y, H, np.diag(R), niters=niters)

    print '... all done ...'
    sys.exit(0)
###############################################################

###############################################################
if __name__ == "__main__":
	main()
###############################################################
